spring.data.mongodb.uri=mongodb+srv://pawankushwah23713_db_user:DE43a2bAy8QZhR7s@cluster0.qvpqpxd.mongodb.net/chatapp?retryWrites=true&w=majority
server.port=8080
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
cloudinary.cloud_name=dgjpkuhof
cloudinary.api_key=Y614712415662633
cloudinary.api_secret=GVqPVOMvM1rFFf1vsJoCOAQ8EMI
