spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
server.port=${PORT:8080}

spring.servlet.multipart.enabled=${SPRING_SERVLET_MULTIPART_ENABLED}
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}



cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
