spring.data.mongodb.uri=${MONGO_URI}
server.port=${PORT:8080}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
cloudinary.cloud_name=dgjpkuhof
cloudinary.api_key=Y614712415662633
cloudinary.api_secret=GVqPVOMvM1rFFf1vsJoCOAQ8EMI
